//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlimmeMeterPortaal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measurement
    {
        public string DeviceID { get; set; }
        public Nullable<decimal> LeveringLaag { get; set; }
        public Nullable<decimal> LeveringNormaal { get; set; }
        public decimal LeveringTotaal { get; set; }
        public decimal Meterstand { get; set; }
        public Nullable<decimal> Temperatuur { get; set; }
        public System.DateTime LeveringDatum { get; set; }
        public int UTC_Offset { get; set; }
        public int LeveringUur { get; set; }
        public int LeveringDag { get; set; }
        public int LeveringMaand { get; set; }
        public int LeveringJaar { get; set; }
        public int Aantalmetingen { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
