//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlimmeMeterPortaal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgressBar
    {
        public string DeviceID { get; set; }
        public int APIcallsTODO { get; set; }
        public int APIcallsDONE { get; set; }
        public Nullable<decimal> Progress { get; set; }
        public string Message01 { get; set; }
        public string Message02 { get; set; }
        public string Message03 { get; set; }
        public string Message04 { get; set; }
        public string Message05 { get; set; }
        public string Guid { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
